# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ca18ae7a6e38d9afc7049a1636c4c3b24842da910158dcf8ce5d5c7214ab82a9a9b77ef524ba78a2585e6d819ac893de4b5608b45911dc99d5ac43c6057a72e

test:
  secret_key_base: 0cea9d260c92ed8e013a12eeba00633dd69b7c2e6b52933e1d875d7c88a7417274ded6c3a8fcb11ec75b1c5e142d50072221eb3ca9e0b7e0b2363fbdf7fc9764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
